/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class DupHelper */

#ifndef _Included_DupHelper
#define _Included_DupHelper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     DupHelper
 * Method:    reopen
 * Signature: (Ljava/lang/String;IZ)V
 */
JNIEXPORT void JNICALL Java_DupHelper_reopen
  (JNIEnv *, jclass, jstring, jint, jboolean);

#ifdef __cplusplus
}
#endif
#endif
